name = "fluentra-worker"
type = "javascript"
account_id = "bb8b1cea5cc1df2ebd8dc4a60eaa9e2b"
workers_dev = true
route = "https://www.fluentra.ro/*"
compatibility_date = "2025-09-16"

# Serve static files from Vite build
[site]
bucket = "./dist"
entry-point = "workers-site"
