name: Deploy Vite site to GitHub Pages (Custom Domain)

on:
  push:
    branches:
      - main  # Runs when you push to main branch

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Predeploy
        run: npm run predeploy

      - name: Deploy
        run: npm run deploy

      - name: Add CNAME for custom domain
        run: echo "www.fluentra.ro" > dist/CNAME

      - name: Disable Jekyll (fix assets on GitHub Pages)
        run: touch dist/.nojekyll

      - name: Upload GitHub Pages artifact
        uses: actions/upload-artifact@v4
        with:
          path: ./dist
          name: github-pages

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
